export const solutionsList = [
  {
    id: 1,
    title_fr: 'Dechets toilette',
    title_en: 'Dechets toilette (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 2,
    title_fr: "Grilles d'eau pluvial",
    title_en: "Grilles d'eau pluvial (en)",
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 3,
    title_fr: 'Coût des dechetterie',
    title_en: 'Coût des dechetterie (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 4,
    title_fr: 'Pesticide agricole',
    title_en: 'Pesticide agricole (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 5,
    title_fr: 'Dechets toilette',
    title_en: 'Dechets toilette (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 6,
    title_fr: "Grilles d'eau pluvial",
    title_en: "Grilles d'eau pluvial (en)",
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 7,
    title_fr: 'Coût des dechetterie',
    title_en: 'Coût des dechetterie (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 8,
    title_fr: 'Pesticide agricole',
    title_en: 'Pesticide agricole (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 9,
    title_fr: 'Dechets toilette',
    title_en: 'Dechets toilette (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 10,
    title_fr: "Grilles d'eau pluvial",
    title_en: "Grilles d'eau pluvial (en)",
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 11,
    title_fr: 'Coût des dechetterie',
    title_en: 'Coût des dechetterie (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 12,
    title_fr: 'Pesticide agricole',
    title_en: 'Pesticide agricole (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 13,
    title_fr: 'Dechets toilette',
    title_en: 'Dechets toilette (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 14,
    title_fr: "Grilles d'eau pluvial",
    title_en: "Grilles d'eau pluvial (en)",
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 15,
    title_fr: 'Coût des dechetterie',
    title_en: 'Coût des dechetterie (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 16,
    title_fr: 'Pesticide agricole',
    title_en: 'Pesticide agricole (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 17,
    title_fr: 'Dechets toilette',
    title_en: 'Dechets toilette (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 18,
    title_fr: "Grilles d'eau pluvial",
    title_en: "Grilles d'eau pluvial (en)",
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 19,
    title_fr: 'Coût des dechetterie',
    title_en: 'Coût des dechetterie (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 20,
    title_fr: 'Pesticide agricole',
    title_en: 'Pesticide agricole (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 21,
    title_fr: 'Dechets toilette',
    title_en: 'Dechets toilette (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 22,
    title_fr: "Grilles d'eau pluvial",
    title_en: "Grilles d'eau pluvial (en)",
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 23,
    title_fr: 'Coût des dechetterie',
    title_en: 'Coût des dechetterie (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
  {
    id: 24,
    title_fr: 'Pesticide agricole',
    title_en: 'Pesticide agricole (en)',
    sanitation_label: true,
    wild_landfill_label: false,
    agricultural_label: false,
    other_label: false,
    food_packaging_label: false,
    cigarette_butts_label: null,
  },
]
